from setuptools import setup, find_packages

setup(
    name='AudioX',
    version='0.1.0',
    url='https://github.com/ZeyueT/AudioX.git',
    author='AudioX, HKUST',
    description='Training and inference tools for generative audio models from AudioX',
    packages=find_packages(),  
    install_requires=[
        'accelerate>=0.25.0',  # For CPU offloading (VRAM optimization)
        'psutil>=5.9.0',       # For system memory detection
        'aeiou',
        'alias-free-torch==0.0.6',
        'auraloss==0.4.0',
        'descript-audio-codec==1.0.0',
        'decord==0.6.0',
        'einops',
        'einops_exts',
        'ema-pytorch==0.2.3',
        'encodec==0.1.1',
        'gradio==4.44.1',
        'gradio_client==1.3.0',
        'huggingface_hub',
        'importlib-resources==5.12.0',
        'k-diffusion==0.1.1',
        'laion-clap==1.1.6',
        'local-attention==1.8.6',
        'pandas==2.0.2',
        'pedalboard==0.9.14',
        'prefigure==0.0.9',
        'pytorch_lightning==2.4.0',
        'PyWavelets==1.4.1',
        'safetensors',
        'sentencepiece==0.1.99',
        'torch>=2.0.1',
        'torchaudio>=2.0.2',
        'torchmetrics==0.11.4',
        'tqdm',
        'transformers',
        'v-diffusion-pytorch==0.0.2',
        'vector-quantize-pytorch==1.9.14',
        'wandb',
        'webdataset==0.2.48',
        'x-transformers<1.27.0',
    ],

)